config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root "feeds#index"
	resources :feeds do
		resources :entries, only: [:index, :show]
	end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :feed
end

app/models/feed.rb
class Feed < ActiveRecord::Base
	has_many :entries, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_action :set_feed, only: :index
	def index
		@entries = @feed.entries.order("published desc")
	end

	def show
		@entry = Entry.find(params[:id])
	end

	private
		def set_feed
			@feed = Feed.find(params[:feed_id])
		end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:name, :url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/entries/index.html.erb
<div class = "container">
	<% @entries.each do |entry| %>
		<div class = "panel panel-default">
			<div class = "panel-body">
				<%= link_to entry.title, feed_entry_path(entry.feed_id, entry) %> - <i>published <%= time_ago_in_words(entry.published) %> ago.</i>
			</div>
		</div>
	<%end%>
</div>

app/views/entries/show.html.erb
<div class = "container">
	<h3><%= link_to @entry.title, @entry.url %></h3>
	<i>published on <%= @entry.published%> by <%= @entry.author %></i>
	<p>
		<%= @entry.content.html_safe unless @entry.content.nil? %>
	</p>
</div>

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= feed.url %></td>
        <td><%= feed.description %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @feed.description %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/_header.html.erb
<div class = "pull-right">
	<% if user_signed_in? %>
		<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Log In", new_user_session_path %>
		<%= link_to "Sign Up", new_user_registration_path %>
	<% end %>
</div>

app/views/layouts/_messages.html.erb
<% if flash.present? %>
	<% flash.each do |key, value| %> 
		<p id="<%= key.to_s %>"><%= value.to_s %></p>
	<%end%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Feedreader</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>
		<%= render "layouts/messages"%>
		<%= yield %>

	</body>
</html>